# PostgreSQL.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("RAILS_DATABASE_HOST", 'localhost') %>
  port: <%= ENV.fetch("RAILS_DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("RAILS_DATABASE_USERNAME", 'postgres') %>
  password: <%= ENV.fetch("RAILS_DATABASE_PASSWORD", 'postgres') %>

development:
  <<: *default
  database: <%= ENV.fetch("RAILS_DATABASE_NAME", 'message_me-development') %>

test: &test
  <<: *default
  database: message_me_test

production:
  <<: *default
  database: message_me_production
  username: message_me
  password: <%= ENV["MESSAGE_ME_DATABASE_PASSWORD"] %>
